name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-build:
    runs-on: ubuntu-latest  # Ubuntu-based runner for Flutter

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Cache Flutter dependencies to avoid re-downloading them
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ./build  # Cache the build directory in the root of the project
        key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}  # Adjust the path to pubspec.yaml
        restore-keys: |
          ${{ runner.os }}-flutter-

    # Set up Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.27.1
    - run: flutter --version

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get  # No need to cd into flutter-app since the files are now at the root

    # Build Flutter Web app (or Android, iOS, etc.)
    - name: Build Flutter Web
      run: |
        flutter build web --release  # Build the web app directly from the root

    # Deploy to GitHub Pages (for Flutter Web)
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        branch: gh-pages  # The GitHub Pages branch
        folder: build/web  # Adjust the path to the web build output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optionally, you can add additional build steps for Android, iOS, or other platforms