name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: |
          cd flutter-app  # Change to the Flutter project directory
          flutter pub get

      - name: Build Flutter web app
        run: |
          cd flutter-app  # Change to the Flutter project directory
          flutter build web

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages  # The GitHub Pages branch
          folder: flutter-app/build/web  # The folder containing the Flutter web build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}