name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-build:
    runs-on: ubuntu-latest  # Ubuntu-based runner for Flutter

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Cache Flutter dependencies to avoid re-downloading them
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ./flutter-app/build  # Cache the build directory inside flutter-app
        key: ${{ runner.os }}-flutter-${{ hashFiles('flutter-app/**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    # Set up Flutter SDK
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Specify the Flutter version you need

    # Install dependencies
    - name: Install dependencies
      run: |
        cd flutter-app  # Navigate to the flutter-app directory
        flutter pub get


    # Build Flutter Web app (or Android, iOS, etc.)
    - name: Build Flutter Web
      run: |
        cd flutter-app  # Navigate to the flutter-app directory
        flutter build web --release
        # For Android, use flutter build apk --release (and for iOS, flutter build ios --release)

    # Deploy to GitHub Pages (for Flutter Web)
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with:
        branch: gh-pages  # The GitHub Pages branch
        folder: flutter-app/build/web  # Folder containing the Flutter Web build output
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optionally, you can add additional build steps for Android, iOS, or other platforms